### PR TITLE
Fix typo in YAML 1.1 bool spec

### PR DESCRIPTION
**Pull request by aaubry**
Fixes a type that was causing a missing case and also resulted in a duplicate test case.

### CODE REVIEW

**Comment by perlpunk** [comment]
Thanks!
merged and updated gh-pages

**Comment by perlpunk** [comment]
btw, congratulations to YamlDotNet! Now on https://matrix.yaml.io/

**Comment by aaubry** [comment]
> btw, congratulations to YamlDotNet! Now on https://matrix.yaml.io/

That's very cool! Credits should go to @am11 who did all the work of integrating the test suite and fixing the bugs that were identified 👍

**Comment by aaubry** [comment]
Btw, I have integrated these tests into my ongoing work on schemas and it has been very helpful. I even discovered an unrelated bug thanks to the additional test cases. Thanks for putting the effort to build this!

**Pull request merged**
